language: julia
os:
    - linux
    - osx
julia:
    - 0.4
    - nightly
notifications:
    email: false

after_success:
- julia -e 'cd(Pkg.dir("DetectionTheory")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(process_folder())'
